build:
  enabled: false

deploy:
  replicas: 1
  route:
    enabled: false
  env:
    # Env vars to connect to Artemis
    - name: JBOSS_MESSAGING_CONNECTOR_HOST
      value: "artemis"
    - name: JBOSS_MESSAGING_CONNECTOR_PORT
      value: "61616"